version: '3.8'

services:
  db:
    image: postgres
    container_name: prod-grade-db
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db.prod
  api:
    container_name: prod-grade-api
    hostname: api
    restart: always
    build:
      context: api
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    env_file:
      - .env.prod
    depends_on:
      - db
  trainees:
    container_name: trainees
    hostname: trainees
    build:
      context: .
      dockerfile: Dockerfile.trainees
  nginx:
    container_name: nginx
    hostname: nginx
    build: nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    ports:
      - 8080:8080
    depends_on:
      - api
      - trainees

volumes:
  postgres_data:
  static_volume:
  media_volume:
