FROM node:alpine AS build

WORKDIR /home/src/app

COPY apps/trainees ./apps/trainees
COPY package.json package-lock.json nx.json tsconfig.base.json jest.preset.js jest.config.ts ./

RUN npm install
RUN npx nx run trainees:build


FROM nginx:latest AS deploy

COPY --from=build /home/src/app/dist/apps/trainees /usr/share/nginx/html

