FROM python:3.11.4-slim-buster

ARG USER_NAME
RUN useradd -ms /bin/bash ${USER_NAME}
WORKDIR /usr/src/app/


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

USER ${USER_NAME}

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
