FROM python:3.11.4-slim-buster

ARG USER_NAME
RUN useradd -ms /bin/bash ${USER_NAME}
WORKDIR /usr/src/app/


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY ./requirements.core.txt .
COPY ./requirements.dev.txt .
RUN pip install -Ur requirements.dev.txt

COPY ./entrypoint.dev.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.dev.sh
RUN chmod +x /usr/src/app/entrypoint.dev.sh

USER ${USER_NAME}

ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]
